# Generated by Django 2.2.11 on 2020-06-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_title', models.CharField(max_length=50)),
                ('ans_text', models.CharField(max_length=200)),
                ('posted_by', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_title', models.CharField(max_length=50)),
                ('ques_text', models.CharField(max_length=200)),
                ('posted_by', models.CharField(max_length=20)),
            ],
        ),
    ]
